spring:
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: discovery-server
server.port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false